import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('forgeDesk', {
  listProjects: () => ipcRenderer.invoke('projects:list'),
  createProject: (input: { name: string; workspacePath: string; repositories: ScannedRepository[] }) => ipcRenderer.invoke('projects:create', input),
  updateProject: (input: { id: string; name?: string; workspacePath?: string; description?: string; owner?: string }) => ipcRenderer.invoke('projects:update', input),
  deleteProject: (projectId: string) => ipcRenderer.invoke('projects:delete', projectId),
  listRepositories: (projectId?: string) => ipcRenderer.invoke('repositories:list', projectId),
  getRepositoryDetail: (repositoryId: string) => ipcRenderer.invoke('repository:detail', repositoryId),
  listRepositoryCommits: (repositoryId: string, options?: { startDate?: string; endDate?: string; branchName?: string }) =>
    ipcRenderer.invoke('repository:commits', repositoryId, options),
  getRepositoryCommitGraph: (repositoryId: string, options?: { startDate?: string; endDate?: string; branchName?: string }) =>
    ipcRenderer.invoke('repository:commit-graph', repositoryId, options),
  syncRepositoryRemote: (repositoryId: string) => ipcRenderer.invoke('repository:sync-remote', repositoryId),
  saveRepositoryRemote: (input: RepositoryRemoteInput) => ipcRenderer.invoke('repository:remote:save', input),
  deleteRepositoryRemote: (repositoryId: string, remoteName: string) => ipcRenderer.invoke('repository:remote:delete', repositoryId, remoteName),
  fetchRepositoryRemote: (repositoryId: string, remoteName?: string) => ipcRenderer.invoke('repository:remote:fetch', repositoryId, remoteName),
  runRepositoryGitCommand: (input: GitCommandRequest) => ipcRenderer.invoke('repository:git-command', input),
  getRepositoryWorkspaceStatus: (repositoryId: string) => ipcRenderer.invoke('repository:workspace-status', repositoryId),
  gitAdd: (repositoryId: string, input: GitAddInput) => ipcRenderer.invoke('repository:git-add', repositoryId, input),
  gitCommit: (repositoryId: string, input: GitCommitInput) => ipcRenderer.invoke('repository:git-commit', repositoryId, input),
  gitPush: (repositoryId: string, input: GitPushInput) => ipcRenderer.invoke('repository:git-push', repositoryId, input),
  analyzeRepositoryMerge: (repositoryId: string, input: GitMergeAnalysisInput) => ipcRenderer.invoke('repository:merge-analysis', repositoryId, input),
  gitMerge: (repositoryId: string, input: GitMergeInput) => ipcRenderer.invoke('repository:git-merge', repositoryId, input),
  suggestCommitMessage: (repositoryId: string, input: GitCommitMessageInput) => ipcRenderer.invoke('repository:commit-message:suggest', repositoryId, input),
  suggestConflictResolution: (repositoryId: string, filePath: string) => ipcRenderer.invoke('repository:conflict:suggest', repositoryId, filePath),
  applyConflictResolution: (repositoryId: string, filePath: string, content: string) => ipcRenderer.invoke('repository:conflict:apply', repositoryId, filePath, content),
  listRepositoryCommitFiles: (repositoryId: string, commitHash: string) => ipcRenderer.invoke('repository:commit-files', repositoryId, commitHash),
  getRepositoryCommitDiff: (repositoryId: string, commitHash: string, filePath: string, oldPath?: string, status?: string) =>
    ipcRenderer.invoke('repository:commit-diff', repositoryId, commitHash, filePath, oldPath, status),
  getProjectSummary: (projectId: string, range?: { startDate?: string; endDate?: string }) => ipcRenderer.invoke('project:summary', projectId, range),
  analyzeProjectGit: (projectId: string) => ipcRenderer.invoke('project:analyze-git', projectId),
  listProjectPeople: (projectId: string) => ipcRenderer.invoke('project:people', projectId),
  listProjectContributorIdentities: (projectId: string) => ipcRenderer.invoke('project:contributor-identities', projectId),
  listProjectBranchTags: (projectId: string) => ipcRenderer.invoke('project:branch-tags', projectId),
  saveProjectBranchTag: (input: { id?: string; projectId: string; label: string; branchName: string; color: string }) => ipcRenderer.invoke('project:branch-tag:save', input),
  deleteProjectBranchTag: (projectId: string, tagId: string) => ipcRenderer.invoke('project:branch-tag:delete', projectId, tagId),
  listServiceConnections: () => ipcRenderer.invoke('service:connections:list'),
  saveServiceConnection: (input: ServiceConnectionInput) => ipcRenderer.invoke('service:connection:save', input),
  deleteServiceConnection: (connectionId: string) => ipcRenderer.invoke('service:connection:delete', connectionId),
  testServiceConnection: (connectionId: string) => ipcRenderer.invoke('service:connection:test', connectionId),
  listAllProjectServices: () => ipcRenderer.invoke('service:services:list'),
  listProjectServices: (projectId: string) => ipcRenderer.invoke('project:services:list', projectId),
  saveProjectService: (input: ProjectServiceInput) => ipcRenderer.invoke('project:service:save', input),
  bindProjectService: (input: { projectId: string; serviceId: string; repositoryId?: string }) => ipcRenderer.invoke('project:service:bind', input),
  syncProjectServices: (connectionId?: string) => ipcRenderer.invoke('project:services:sync', connectionId),
  checkProjectServices: (projectId?: string) => ipcRenderer.invoke('service:monitor:check', projectId),
  listLatestServiceMonitorChecks: (projectId: string) => ipcRenderer.invoke('service:monitor:latest', projectId),
  listServiceMonitorHistory: (projectId: string) => ipcRenderer.invoke('service:monitor:history', projectId),
  listAllServiceMonitorHistory: () => ipcRenderer.invoke('service:monitor:history:all'),
  listServiceEnvironmentLogs: (serviceId: string, environmentName: string) => ipcRenderer.invoke('service:environment:logs', serviceId, environmentName),
  saveProjectPerson: (input: { id?: string; projectId: string; displayName: string; role?: string; identities: Array<{ name: string; email: string }> }) =>
    ipcRenderer.invoke('project:person:save', input),
  deleteProjectPerson: (projectId: string, personId: string) => ipcRenderer.invoke('project:person:delete', projectId, personId),
  scanRepositories: (paths: string[]) => ipcRenderer.invoke('repositories:scan', paths),
  scanWorkspace: (rootPath: string) => ipcRenderer.invoke('repositories:scan-workspace', rootPath),
  configureRepositoryIdentity: (localPath: string, identity: { userName: string; userEmail: string }) =>
    ipcRenderer.invoke('repository:configure-identity', localPath, identity),
  clearRepositoryIdentity: (localPath: string) => ipcRenderer.invoke('repository:clear-identity', localPath),
  selectDirectory: () => ipcRenderer.invoke('dialog:select-directory'),
  selectFile: () => ipcRenderer.invoke('dialog:select-file'),
  getGitSetupStatus: () => ipcRenderer.invoke('git:setup-status'),
  configureGitIdentity: (identity: { userName: string; userEmail: string }) => ipcRenderer.invoke('git:configure-identity', identity),
  getAiSettings: () => ipcRenderer.invoke('settings:ai:get'),
  saveAiSettings: (input: AiSettingsInput) => ipcRenderer.invoke('settings:ai:save', input),
  generateSshKey: (input: string | SshKeyGenerationInput) => ipcRenderer.invoke('ssh:generate-key', input),
  copySshPublicKey: (publicKeyPath: string) => ipcRenderer.invoke('ssh:copy-public-key', publicKeyPath),
  copySshKeyPath: (path: string, kind: SshKeyKind) => ipcRenderer.invoke('ssh:copy-key-path', path, kind),
  importSshKey: (input: SshKeyImportInput) => ipcRenderer.invoke('ssh:import-key', input),
  deleteSshKey: (path: string, kind: SshKeyKind) => ipcRenderer.invoke('ssh:delete-key', path, kind),
  saveSshPrivateKeyPassphrase: (path: string, passphrase: string) => ipcRenderer.invoke('ssh:save-private-key-passphrase', path, passphrase),
  clearSshPrivateKeyPassphrase: (path: string) => ipcRenderer.invoke('ssh:clear-private-key-passphrase', path),
  fixSshPrivateKeyPermissions: (path: string) => ipcRenderer.invoke('ssh:fix-private-key-permissions', path),
  deriveSshPublicKey: (privateKeyPath: string) => ipcRenderer.invoke('ssh:derive-public-key', privateKeyPath),
  readSshConfig: () => ipcRenderer.invoke('ssh:read-config'),
  writeSshConfig: (content: string) => ipcRenderer.invoke('ssh:write-config', content),
  openSshDirectory: () => ipcRenderer.invoke('ssh:open-directory'),
  openGitDownload: () => ipcRenderer.invoke('external:open-git-download')
})
