import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('forgeDesk', {
  listProjects: () => ipcRenderer.invoke('projects:list'),
  createProject: (input: { name: string; workspacePath: string; repositories: ScannedRepository[] }) => ipcRenderer.invoke('projects:create', input),
  createEmptyProject: (input: { name: string; parentPath: string }) => ipcRenderer.invoke('projects:create-empty', input),
  createProjectFromRemote: (input: { name: string; remoteUrl: string; parentPath: string }) => ipcRenderer.invoke('projects:create-from-remote', input),
  updateProject: (input: { id: string; name?: string; workspacePath?: string; description?: string; owner?: string }) => ipcRenderer.invoke('projects:update', input),
  setProjectFavorite: (input: { id: string; isFavorite: boolean }) => ipcRenderer.invoke('projects:favorite', input),
  listProjectGroups: () => ipcRenderer.invoke('project-groups:list'),
  saveProjectGroup: (input: ProjectGroupInput) => ipcRenderer.invoke('project-group:save', input),
  deleteProjectGroup: (groupId: string) => ipcRenderer.invoke('project-group:delete', groupId),
  reorderProjectGroups: (groupIds: string[]) => ipcRenderer.invoke('project-groups:reorder', groupIds),
  setProjectGroup: (input: { projectId: string; groupId: string | null }) => ipcRenderer.invoke('project:group:set', input),
  listCodexProjectLinks: () => ipcRenderer.invoke('codex-project-link:list'),
  saveCodexProjectLink: (input: CodexProjectLinkInput) => ipcRenderer.invoke('codex-project-link:save', input),
  deleteCodexProjectLink: (cwd: string) => ipcRenderer.invoke('codex-project-link:delete', cwd),
  deleteProject: (projectId: string) => ipcRenderer.invoke('projects:delete', projectId),
  rescanProjectRepositories: (projectId: string) => ipcRenderer.invoke('project:repositories:rescan', projectId),
  initializeProjectRepository: (projectId: string) => ipcRenderer.invoke('project:repository:init', projectId),
  listRepositories: (projectId?: string) => ipcRenderer.invoke('repositories:list', projectId),
  getRepositoryDetail: (repositoryId: string) => ipcRenderer.invoke('repository:detail', repositoryId),
  listRepositoryCommits: (repositoryId: string, options?: { startDate?: string; endDate?: string; branchName?: string }) =>
    ipcRenderer.invoke('repository:commits', repositoryId, options),
  getRepositoryCommitGraph: (repositoryId: string, options?: { startDate?: string; endDate?: string; branchName?: string }) =>
    ipcRenderer.invoke('repository:commit-graph', repositoryId, options),
  syncRepositoryRemote: (repositoryId: string) => ipcRenderer.invoke('repository:sync-remote', repositoryId),
  saveRepositoryRemote: (input: RepositoryRemoteInput) => ipcRenderer.invoke('repository:remote:save', input),
  deleteRepositoryRemote: (repositoryId: string, remoteName: string) => ipcRenderer.invoke('repository:remote:delete', repositoryId, remoteName),
  fetchRepositoryRemote: (repositoryId: string, remoteName?: string, operationId?: string) => ipcRenderer.invoke('repository:remote:fetch', repositoryId, remoteName, operationId),
  switchRepositoryBranch: (repositoryId: string, input: GitBranchSwitchInput) => ipcRenderer.invoke('repository:branch:switch', repositoryId, input),
  runRepositoryGitCommand: (input: GitCommandRequest) => ipcRenderer.invoke('repository:git-command', input),
  getRepositoryWorkspaceStatus: (repositoryId: string) => ipcRenderer.invoke('repository:workspace-status', repositoryId),
  gitAdd: (repositoryId: string, input: GitAddInput) => ipcRenderer.invoke('repository:git-add', repositoryId, input),
  gitCommit: (repositoryId: string, input: GitCommitInput) => ipcRenderer.invoke('repository:git-commit', repositoryId, input),
  gitPush: (repositoryId: string, input: GitPushInput, operationId?: string) => ipcRenderer.invoke('repository:git-push', repositoryId, input, operationId),
  gitPushTask: (repositoryId: string, input: GitPushInput, operationId: string) => ipcRenderer.invoke('repository:git-push-task', repositoryId, input, operationId),
  cancelRepositoryGitOperation: (operationId: string) => ipcRenderer.invoke('repository:git-operation:cancel', operationId),
  listProjectGitTasks: (projectId?: string) => ipcRenderer.invoke('project:git-tasks:list', projectId),
  getProjectGitTask: (taskId: string) => ipcRenderer.invoke('project:git-task:get', taskId),
  saveProjectGitTask: (task: ProjectGitTaskLog) => ipcRenderer.invoke('project:git-task:save', task),
  deleteProjectGitTask: (taskId: string) => ipcRenderer.invoke('project:git-task:delete', taskId),
  clearProjectGitTasks: () => ipcRenderer.invoke('project:git-tasks:clear'),
  onProjectGitTaskUpdated: (listener: (task: ProjectGitTaskLog) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, task: ProjectGitTaskLog): void => listener(task)
    ipcRenderer.on('project-git-tasks:updated', wrapped)
    return () => ipcRenderer.removeListener('project-git-tasks:updated', wrapped)
  },
  getRepositoryDeploymentApprovalConfig: (repositoryId: string) => ipcRenderer.invoke('repository:deployment-approval:config:get', repositoryId),
  saveRepositoryDeploymentApprovalConfig: (input: DeploymentApprovalConfig) => ipcRenderer.invoke('repository:deployment-approval:config:save', input),
  analyzeRepositoryDeploymentApproval: (repositoryId: string, input?: { manualBaselineSha?: string }) =>
    ipcRenderer.invoke('repository:deployment-approval:analyze', repositoryId, input),
  executeRepositoryDeploymentApproval: (repositoryId: string, input: { reviewedHeadSha: string; baselineSha: string }) =>
    ipcRenderer.invoke('repository:deployment-approval:execute', repositoryId, input),
  listRepositoryDeploymentApprovals: (repositoryId: string) => ipcRenderer.invoke('repository:deployment-approvals:list', repositoryId),
  analyzeRepositoryMerge: (repositoryId: string, input: GitMergeAnalysisInput) => ipcRenderer.invoke('repository:merge-analysis', repositoryId, input),
  gitMerge: (repositoryId: string, input: GitMergeInput) => ipcRenderer.invoke('repository:git-merge', repositoryId, input),
  suggestCommitMessage: (repositoryId: string, input: GitCommitMessageInput) => ipcRenderer.invoke('repository:commit-message:suggest', repositoryId, input),
  prepareRepositoryRelease: (repositoryId: string, input?: RepositoryReleasePrepareInput) => ipcRenderer.invoke('repository:release:prepare', repositoryId, input),
  recommendRepositoryReleaseTag: (repositoryId: string) => ipcRenderer.invoke('repository:release-tag:recommend', repositoryId),
  suggestRepositoryRelease: (repositoryId: string, input?: RepositoryReleaseSuggestionInput) => ipcRenderer.invoke('repository:release:suggest', repositoryId, input),
  publishRepositoryRelease: (repositoryId: string, input: RepositoryReleasePublishInput) => ipcRenderer.invoke('repository:release:publish', repositoryId, input),
  startRepositoryReleasePublishTask: (repositoryId: string, input: RepositoryReleasePublishInput) => ipcRenderer.invoke('repository:release-publish-task:start', repositoryId, input),
  listRepositoryReleasePublishTasks: (repositoryId?: string) => ipcRenderer.invoke('repository:release-publish-tasks:list', repositoryId),
  getRepositoryReleasePublishTask: (taskId: string) => ipcRenderer.invoke('repository:release-publish-task:get', taskId),
  cancelRepositoryReleasePublishTask: (taskId: string) => ipcRenderer.invoke('repository:release-publish-task:cancel', taskId),
  getRepositoryCodemagicBinding: (repositoryId: string) => ipcRenderer.invoke('repository:codemagic-binding:get', repositoryId),
  saveRepositoryCodemagicBinding: (input: CodemagicRepositoryBindingInput) => ipcRenderer.invoke('repository:codemagic-binding:save', input),
  deleteRepositoryCodemagicBinding: (repositoryId: string) => ipcRenderer.invoke('repository:codemagic-binding:delete', repositoryId),
  suggestConflictResolution: (repositoryId: string, filePath: string) => ipcRenderer.invoke('repository:conflict:suggest', repositoryId, filePath),
  applyConflictResolution: (repositoryId: string, filePath: string, content: string) => ipcRenderer.invoke('repository:conflict:apply', repositoryId, filePath, content),
  listRepositoryCommitFiles: (repositoryId: string, commitHash: string) => ipcRenderer.invoke('repository:commit-files', repositoryId, commitHash),
  getRepositoryCommitDiff: (repositoryId: string, commitHash: string, filePath: string, oldPath?: string, status?: string) =>
    ipcRenderer.invoke('repository:commit-diff', repositoryId, commitHash, filePath, oldPath, status),
  getProjectSummary: (projectId: string, range?: { startDate?: string; endDate?: string }) => ipcRenderer.invoke('project:summary', projectId, range),
  analyzeProjectGit: (projectId: string) => ipcRenderer.invoke('project:analyze-git', projectId),
  listProjectPeople: (projectId: string) => ipcRenderer.invoke('project:people', projectId),
  listProjectContributorIdentities: (projectId: string) => ipcRenderer.invoke('project:contributor-identities', projectId),
  listProjectBranchTags: (projectId: string) => ipcRenderer.invoke('project:branch-tags', projectId),
  saveProjectBranchTag: (input: { id?: string; projectId: string; label: string; branchName: string; color: string }) => ipcRenderer.invoke('project:branch-tag:save', input),
  deleteProjectBranchTag: (projectId: string, tagId: string) => ipcRenderer.invoke('project:branch-tag:delete', projectId, tagId),
  listProjectTerminalCommands: (projectId: string) => ipcRenderer.invoke('project:terminal-commands:list', projectId),
  saveProjectTerminalCommand: (input: ProjectTerminalCommandInput) => ipcRenderer.invoke('project:terminal-command:save', input),
  deleteProjectTerminalCommand: (projectId: string, commandId: string) => ipcRenderer.invoke('project:terminal-command:delete', projectId, commandId),
  getPlaneSettings: () => ipcRenderer.invoke('plane:settings:get'),
  savePlaneSettings: (input: PlaneSettingsInput) => ipcRenderer.invoke('plane:settings:save', input),
  testPlaneSettings: (input?: PlaneSettingsInput) => ipcRenderer.invoke('plane:settings:test', input),
  listPlaneProjects: (workspaceSlug: string) => ipcRenderer.invoke('plane:projects:list', workspaceSlug),
  getProjectPlaneBinding: (projectId: string) => ipcRenderer.invoke('plane:binding:get', projectId),
  saveProjectPlaneBinding: (input: PlaneProjectBindingInput) => ipcRenderer.invoke('plane:binding:save', input),
  deleteProjectPlaneBinding: (projectId: string) => ipcRenderer.invoke('plane:binding:delete', projectId),
  getPlaneProjectContent: (projectId: string) => ipcRenderer.invoke('plane:project-content:get', projectId),
  openPlane: (projectId?: string) => ipcRenderer.invoke('plane:open', projectId),
  getProjectCloudflareSettings: (projectId: string) => ipcRenderer.invoke('project:cloudflare:settings:get', projectId),
  saveProjectCloudflareSettings: (input: ProjectCloudflareSettingsInput) => ipcRenderer.invoke('project:cloudflare:settings:save', input),
  deleteProjectCloudflareSettings: (projectId: string) => ipcRenderer.invoke('project:cloudflare:settings:delete', projectId),
  testProjectCloudflareSettings: (projectId: string, input?: ProjectCloudflareSettingsInput) => ipcRenderer.invoke('project:cloudflare:settings:test', projectId, input),
  listProjectCloudflareDnsRecords: (projectId: string) => ipcRenderer.invoke('project:cloudflare:dns-records:list', projectId),
  saveProjectCloudflareDnsRecord: (projectId: string, input: CloudflareDnsRecordInput) => ipcRenderer.invoke('project:cloudflare:dns-record:save', projectId, input),
  deleteProjectCloudflareDnsRecord: (projectId: string, recordId: string) => ipcRenderer.invoke('project:cloudflare:dns-record:delete', projectId, recordId),
  getProjectFirebaseReleaseSettings: (projectId: string) => ipcRenderer.invoke('project:firebase-release:settings:get', projectId),
  saveProjectFirebaseReleaseSettings: (input: ProjectFirebaseReleaseSettingsInput) => ipcRenderer.invoke('project:firebase-release:settings:save', input),
  deleteProjectFirebaseReleaseSettings: (projectId: string) => ipcRenderer.invoke('project:firebase-release:settings:delete', projectId),
  listDataSourceConnections: () => ipcRenderer.invoke('data-source:connections:list'),
  saveDataSourceConnection: (input: DataSourceConnectionInput) => ipcRenderer.invoke('data-source:connection:save', input),
  deleteDataSourceConnection: (connectionId: string) => ipcRenderer.invoke('data-source:connection:delete', connectionId),
  testDataSourceConnection: (connectionId: string) => ipcRenderer.invoke('data-source:connection:test', connectionId),
  listDatabaseTables: (connectionId: string) => ipcRenderer.invoke('data-source:database:tables', connectionId),
  previewDatabaseTable: (connectionId: string, input: { schema?: string; table: string; limit?: number; offset?: number }) =>
    ipcRenderer.invoke('data-source:database:preview', connectionId, input),
  runDataSourceSql: (connectionId: string, input: { sql: string; limit?: number }) => ipcRenderer.invoke('data-source:database:sql', connectionId, input),
  scanRedisKeys: (connectionId: string, input?: { pattern?: string; cursor?: string; limit?: number }) => ipcRenderer.invoke('data-source:redis:keys', connectionId, input),
  previewRedisValue: (connectionId: string, input: { key: string; limit?: number }) => ipcRenderer.invoke('data-source:redis:value', connectionId, input),
  listS3Objects: (connectionId: string, input?: { prefix?: string; continuationToken?: string; limit?: number }) => ipcRenderer.invoke('data-source:s3:objects', connectionId, input),
  previewS3Object: (connectionId: string, input: { key: string }) => ipcRenderer.invoke('data-source:s3:object', connectionId, input),
  listServiceConnections: () => ipcRenderer.invoke('service:connections:list'),
  saveServiceConnection: (input: ServiceConnectionInput) => ipcRenderer.invoke('service:connection:save', input),
  deleteServiceConnection: (connectionId: string) => ipcRenderer.invoke('service:connection:delete', connectionId),
  testServiceConnection: (connectionId: string) => ipcRenderer.invoke('service:connection:test', connectionId),
  listAllProjectServices: () => ipcRenderer.invoke('service:services:list'),
  listProjectServices: (projectId: string) => ipcRenderer.invoke('project:services:list', projectId),
  saveProjectService: (input: ProjectServiceInput) => ipcRenderer.invoke('project:service:save', input),
  saveServiceExternalProjectAlias: (input: ServiceExternalProjectAliasInput) => ipcRenderer.invoke('service:external-project:alias:save', input),
  bindProjectService: (input: { projectId: string; serviceId: string; repositoryId?: string }) => ipcRenderer.invoke('project:service:bind', input),
  syncProjectServices: (connectionId?: string) => ipcRenderer.invoke('project:services:sync', connectionId),
  checkProjectServices: (projectId?: string) => ipcRenderer.invoke('service:monitor:check', projectId),
  listLatestServiceMonitorChecks: (projectId: string) => ipcRenderer.invoke('service:monitor:latest', projectId),
  listServiceMonitorHistory: (projectId: string) => ipcRenderer.invoke('service:monitor:history', projectId),
  listAllServiceMonitorHistory: () => ipcRenderer.invoke('service:monitor:history:all'),
  listServiceEnvironmentLogs: (serviceId: string, environmentName: string) => ipcRenderer.invoke('service:environment:logs', serviceId, environmentName),
  listCachedServiceDeployments: (serviceId: string, options?: ServiceDeploymentListOptions) => ipcRenderer.invoke('service:deployments:cached:list', serviceId, options),
  listServiceDeployments: (serviceId: string, options?: ServiceDeploymentListOptions) => ipcRenderer.invoke('service:deployments:list', serviceId, options),
  runServiceDeploymentAction: (serviceId: string, input: ServiceDeploymentActionInput) => ipcRenderer.invoke('service:deployment:action', serviceId, input),
  listServiceEnvVars: (serviceId: string) => ipcRenderer.invoke('service:env:list', serviceId),
  revealServiceEnvVar: (serviceId: string, envVarId: string) => ipcRenderer.invoke('service:env:reveal', serviceId, envVarId),
  saveServiceEnvVar: (serviceId: string, input: VercelEnvVarInput) => ipcRenderer.invoke('service:env:save', serviceId, input),
  deleteServiceEnvVar: (serviceId: string, envVarId: string) => ipcRenderer.invoke('service:env:delete', serviceId, envVarId),
  addServiceDomain: (serviceId: string, input: VercelDomainInput) => ipcRenderer.invoke('service:domain:add', serviceId, input),
  removeServiceDomain: (serviceId: string, domain: string, removeRedirects?: boolean) => ipcRenderer.invoke('service:domain:remove', serviceId, domain, removeRedirects),
  verifyServiceDomain: (serviceId: string, domain: string) => ipcRenderer.invoke('service:domain:verify', serviceId, domain),
  inspectServiceDomainConfig: (serviceId: string, domain: string) => ipcRenderer.invoke('service:domain:config', serviceId, domain),
  listServiceRuntimeLogs: (serviceId: string, environmentName: string) => ipcRenderer.invoke('service:runtime:logs', serviceId, environmentName),
  inspectProjectDeploymentContext: (repositoryId: string) => ipcRenderer.invoke('project:deployment:context:inspect', repositoryId),
  suggestProjectDeploymentConfig: (repositoryId: string, input: { provider: DeploymentProviderType; sourceMode: DeploymentSourceMode }) =>
    ipcRenderer.invoke('project:deployment:suggest', repositoryId, input),
  listProjectDeploymentTargets: (projectId: string) => ipcRenderer.invoke('project:deployment:targets:list', projectId),
  saveProjectDeploymentTarget: (input: ProjectDeploymentTargetInput) => ipcRenderer.invoke('project:deployment:target:save', input),
  deleteProjectDeploymentTarget: (projectId: string, targetId: string) => ipcRenderer.invoke('project:deployment:target:delete', projectId, targetId),
  prepareProjectDeployment: (input: ProjectDeploymentPrepareInput) => ipcRenderer.invoke('project:deployment:prepare', input),
  startProjectDeploymentTask: (input: ProjectDeploymentTaskStartInput) => ipcRenderer.invoke('project:deployment:task:start', input),
  listProjectDeploymentTasks: (projectId?: string) => ipcRenderer.invoke('project:deployment:tasks:list', projectId),
  getProjectDeploymentTask: (taskId: string) => ipcRenderer.invoke('project:deployment:task:get', taskId),
  cancelProjectDeploymentTask: (taskId: string) => ipcRenderer.invoke('project:deployment:task:cancel', taskId),
  getDockerSnapshot: () => ipcRenderer.invoke('docker:snapshot'),
  getDockerContainerDetail: (containerId: string) => ipcRenderer.invoke('docker:container:detail', containerId),
  createDockerDevEnvironment: (input: DockerDevEnvironmentInput) => ipcRenderer.invoke('docker:dev-environment:create', input),
  listDockerDevEnvironmentTasks: () => ipcRenderer.invoke('docker:dev-environment:tasks'),
  saveDockerResourceNote: (input: DockerResourceNoteInput) => ipcRenderer.invoke('docker:note:save', input),
  deleteDockerResourceNote: (resourceType: DockerResourceType, resourceKey: string) => ipcRenderer.invoke('docker:note:delete', resourceType, resourceKey),
  startDockerWatch: () => ipcRenderer.invoke('docker:watch:start'),
  stopDockerWatch: () => ipcRenderer.invoke('docker:watch:stop'),
  onDockerChanged: (listener: (event: DockerEventSummary) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: DockerEventSummary): void => listener(event)
    ipcRenderer.on('docker:changed', wrapped)
    return () => ipcRenderer.removeListener('docker:changed', wrapped)
  },
  onDockerWatchError: (listener: (event: { message: string }) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: { message: string }): void => listener(event)
    ipcRenderer.on('docker:watch:error', wrapped)
    return () => ipcRenderer.removeListener('docker:watch:error', wrapped)
  },
  onDockerDevEnvironmentProgress: (listener: (event: DockerDevEnvironmentTaskSnapshot) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: DockerDevEnvironmentTaskSnapshot): void => listener(event)
    ipcRenderer.on('docker:dev-environment:progress', wrapped)
    return () => ipcRenderer.removeListener('docker:dev-environment:progress', wrapped)
  },
  saveProjectPerson: (input: { id?: string; projectId: string; displayName: string; role?: string; identities: Array<{ name: string; email: string }> }) =>
    ipcRenderer.invoke('project:person:save', input),
  deleteProjectPerson: (projectId: string, personId: string) => ipcRenderer.invoke('project:person:delete', projectId, personId),
  scanRepositories: (paths: string[]) => ipcRenderer.invoke('repositories:scan', paths),
  scanWorkspace: (rootPath: string) => ipcRenderer.invoke('repositories:scan-workspace', rootPath),
  configureRepositoryIdentity: (localPath: string, identity: { userName: string; userEmail: string }) =>
    ipcRenderer.invoke('repository:configure-identity', localPath, identity),
  clearRepositoryIdentity: (localPath: string) => ipcRenderer.invoke('repository:clear-identity', localPath),
  selectDirectory: () => ipcRenderer.invoke('dialog:select-directory'),
  selectFile: () => ipcRenderer.invoke('dialog:select-file'),
  selectImage: () => ipcRenderer.invoke('dialog:select-image'),
  readClipboardImage: () => ipcRenderer.invoke('clipboard:read-image'),
  readImageData: (imagePath: string) => ipcRenderer.invoke('file:read-image-data', imagePath),
  getGitSetupStatus: () => ipcRenderer.invoke('git:setup-status'),
  configureGitIdentity: (identity: { userName: string; userEmail: string }) => ipcRenderer.invoke('git:configure-identity', identity),
  installGpg: () => ipcRenderer.invoke('gpg:install'),
  importGpgBundle: (input: { sourcePath: string }) => ipcRenderer.invoke('gpg:import-bundle', input),
  copyGpgPublicKey: (fingerprint: string) => ipcRenderer.invoke('gpg:copy-public-key', fingerprint),
  configureGitGpgSigning: (fingerprint: string) => ipcRenderer.invoke('gpg:configure-git-signing', fingerprint),
  getAiSettings: () => ipcRenderer.invoke('settings:ai:get'),
  connectCodexApiServiceToAi: () => ipcRenderer.invoke('settings:ai:connect-codex-api'),
  syncCodexApiServiceToAi: () => ipcRenderer.invoke('settings:ai:sync-codex-api'),
  getInitializationSnapshot: () => ipcRenderer.invoke('initialization:get'),
  listAiProviders: () => ipcRenderer.invoke('ai-providers:list'),
  openAiProvider: (input: { providerId: 'codex'; projectPath?: string }) => ipcRenderer.invoke('ai-providers:open', input),
  getAiProviderQuota: (input: { providerId: 'codex'; accountId?: string; refresh?: boolean }) => ipcRenderer.invoke('ai-providers:quota', input),
  listAiProviderAccountSnapshots: (input: { providerId: 'codex'; refresh?: boolean }) => ipcRenderer.invoke('ai-providers:account-snapshots', input),
  getProjectAiBinding: (input: { projectId: string; providerId: string }) => ipcRenderer.invoke('project-ai-bindings:get', input),
  saveProjectAiBinding: (input: ProjectAiBindingInput) => ipcRenderer.invoke('project-ai-bindings:save', input),
  getCodexAccount: () => ipcRenderer.invoke('codex:account:get'),
  listCodexAccounts: () => ipcRenderer.invoke('codex:accounts:list'),
  importCodexAccount: (input: CodexAccountImportInput) => ipcRenderer.invoke('codex:accounts:import', input),
  createCodexAccount: (input?: { name?: string }) => ipcRenderer.invoke('codex:accounts:create', input),
  activateCodexAccount: (accountId: string) => ipcRenderer.invoke('codex:accounts:activate', accountId),
  removeCodexAccount: (accountId: string) => ipcRenderer.invoke('codex:accounts:remove', accountId),
  verifyCodexAccount: (accountId: string) => ipcRenderer.invoke('codex:accounts:verify', accountId),
  openCodexAccountLogin: (accountId: string) => ipcRenderer.invoke('codex:accounts:login-terminal', accountId),
  getCodexApiService: () => ipcRenderer.invoke('codex:api-service:get'),
  startCodexApiService: (input?: { port?: number; model?: string }) => ipcRenderer.invoke('codex:api-service:start', input),
  stopCodexApiService: () => ipcRenderer.invoke('codex:api-service:stop'),
  rotateCodexApiKey: () => ipcRenderer.invoke('codex:api-service:rotate-key'),
  checkCodexApiService: () => ipcRenderer.invoke('codex:api-service:health'),
  getAiRuntimeStatus: (verify?: boolean) => ipcRenderer.invoke('settings:ai:status', verify),
  getCodexRuntimeStatus: (verify?: boolean) => ipcRenderer.invoke('codex:runtime:status', verify),
  getCodexActivitySnapshot: () => ipcRenderer.invoke('codex:activity:snapshot'),
  listCodexSessions: () => ipcRenderer.invoke('codex:sessions:list'),
  getCodexSession: (sessionId: string) => ipcRenderer.invoke('codex:sessions:get', sessionId),
  toggleCodexSessionPin: (sessionId: string) => ipcRenderer.invoke('codex:sessions:pin', sessionId),
  sendCodexSessionMessage: (input: CodexSessionMessageInput) => ipcRenderer.invoke('codex:sessions:send', input),
  cancelCodexSession: (sessionId: string) => ipcRenderer.invoke('codex:sessions:cancel', sessionId),
  getCodexProjectMonitorSnapshot: () => ipcRenderer.invoke('codex:project-monitor:snapshot'),
  onCodexProjectMonitorUpdated: (listener: (snapshot: CodexProjectMonitorSnapshot) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, snapshot: CodexProjectMonitorSnapshot): void => listener(snapshot)
    ipcRenderer.on('codex:project-monitor:updated', wrapped)
    return () => ipcRenderer.removeListener('codex:project-monitor:updated', wrapped)
  },
  onCodexMonitorAlert: (listener: (alert: CodexUncommittedAlert) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, alert: CodexUncommittedAlert): void => listener(alert)
    ipcRenderer.on('codex:project-monitor:alert', wrapped)
    return () => ipcRenderer.removeListener('codex:project-monitor:alert', wrapped)
  },
  onCodexMonitorFocus: (listener: (alert: CodexUncommittedAlert) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, alert: CodexUncommittedAlert): void => listener(alert)
    ipcRenderer.on('codex:project-monitor:focus', wrapped)
    return () => ipcRenderer.removeListener('codex:project-monitor:focus', wrapped)
  },
  onCodexSessionEvent: (listener: (event: CodexSessionEvent) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: CodexSessionEvent): void => listener(event)
    ipcRenderer.on('codex:sessions:event', wrapped)
    return () => ipcRenderer.removeListener('codex:sessions:event', wrapped)
  },
  listCodexSites: () => ipcRenderer.invoke('codex:sites:list'),
  createCodexSite: (input: CodexSiteCreateInput) => ipcRenderer.invoke('codex:sites:create', input),
  updateCodexSite: (input: CodexSiteUpdateInput) => ipcRenderer.invoke('codex:sites:update', input),
  deleteCodexSite: (siteId: string) => ipcRenderer.invoke('codex:sites:delete', siteId),
  startCodexSitePreview: (siteId: string) => ipcRenderer.invoke('codex:sites:preview:start', siteId),
  stopCodexSitePreview: (siteId: string) => ipcRenderer.invoke('codex:sites:preview:stop', siteId),
  listCodexTasks: () => ipcRenderer.invoke('codex:tasks:list'),
  createCodexTask: (input?: CodexTaskCreateInput) => ipcRenderer.invoke('codex:tasks:create', input),
  renameCodexTask: (input: CodexTaskRenameInput) => ipcRenderer.invoke('codex:tasks:rename', input),
  sendCodexTaskMessage: (input: CodexTaskMessageInput) => ipcRenderer.invoke('codex:tasks:send', input),
  cancelCodexTask: (taskId: string) => ipcRenderer.invoke('codex:tasks:cancel', taskId),
  deleteCodexTask: (taskId: string) => ipcRenderer.invoke('codex:tasks:delete', taskId),
  getCodexTaskEnvironment: (taskId: string) => ipcRenderer.invoke('codex:tasks:environment', taskId),
  onCodexTaskEvent: (listener: (event: CodexTaskEvent) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: CodexTaskEvent): void => listener(event)
    ipcRenderer.on('codex:tasks:event', wrapped)
    return () => ipcRenderer.removeListener('codex:tasks:event', wrapped)
  },
  listOpenRouterModels: () => ipcRenderer.invoke('settings:ai:models:openrouter'),
  saveAiSettings: (input: AiSettingsInput) => ipcRenderer.invoke('settings:ai:save', input),
  getOverviewSnapshot: () => ipcRenderer.invoke('overview:snapshot:get'),
  getMarketDataSnapshot: (period?: '1D' | '1W' | '1M' | '1Y') => ipcRenderer.invoke('market-data:snapshot', period),
  refreshOverviewNews: () => ipcRenderer.invoke('overview:news:refresh'),
  refreshOverviewProjects: () => ipcRenderer.invoke('overview:projects:refresh'),
  getSystemMonitorSnapshot: () => ipcRenderer.invoke('system-monitor:snapshot'),
  listCurrentResourceProcesses: () => ipcRenderer.invoke('system-resource:processes:current'),
  listResourceHistory: (range?: { from?: string; to?: string }) => ipcRenderer.invoke('system-resource:history', range),
  importLegacyResourceHistory: (points: Array<{ checkedAt: string; cpuLoadPercent: number; memoryUsagePercent: number; storageUsagePercent: number }>) => ipcRenderer.invoke('system-resource:history:import', points),
  listProcessResourceHistory: (identityKey: string, range?: { from?: string; to?: string }) => ipcRenderer.invoke('system-resource:process:history', identityKey, range),
  listProcessAnalysis: (range?: { from?: string; to?: string }) => ipcRenderer.invoke('system-resource:analysis', range),
  getResourceRetentionStatus: () => ipcRenderer.invoke('system-resource:retention'),
  signalResourceProcess: (pid: number, force?: boolean) => ipcRenderer.invoke('system-resource:process:signal', pid, force),
  revealResourceProcess: (path: string) => ipcRenderer.invoke('system-resource:process:reveal', path),
  exportProcessAnalysis: (input: { format: 'csv' | 'json'; range?: { from?: string; to?: string } }) => ipcRenderer.invoke('system-resource:analysis:export', input),
  getResourceMonitorSettings: () => ipcRenderer.invoke('system-resource:settings'),
  setResourceLoginStart: (enabled: boolean) => ipcRenderer.invoke('system-resource:login-start:set', enabled),
  getStorageGovernanceOverview: () => ipcRenderer.invoke('storage-governance:overview'),
  listStorageDirectories: (query?: StorageDirectoryQuery) => ipcRenderer.invoke('storage-governance:directories:list', query),
  selectStorageGovernanceRoots: () => ipcRenderer.invoke('storage-governance:root:select'),
  saveStorageGovernanceRoot: (input: { path: string; label?: string; source?: 'manual' | 'project' | 'category' }) => ipcRenderer.invoke('storage-governance:root:save', input),
  deleteStorageGovernanceRoot: (rootId: string) => ipcRenderer.invoke('storage-governance:root:delete', rootId),
  setCleanupCategoryAuthorization: (category: CleanupCategory, enabled: boolean) => ipcRenderer.invoke('storage-governance:category:set', category, enabled),
  startStorageGovernanceScan: (mode: 'quick' | 'deep') => ipcRenderer.invoke('storage-governance:scan:start', mode),
  pauseStorageGovernanceScan: (scanId: string, paused: boolean) => ipcRenderer.invoke('storage-governance:scan:pause', scanId, paused),
  verifyStorageDuplicateGroup: (itemId: string) => ipcRenderer.invoke('storage-governance:duplicate:verify', itemId),
  previewStorageCleanup: (itemIds: string[]) => ipcRenderer.invoke('storage-governance:cleanup:preview', itemIds),
  executeStorageCleanup: (itemIds: string[]) => ipcRenderer.invoke('storage-governance:cleanup:execute', itemIds),
  listStorageCleanupAudit: () => ipcRenderer.invoke('storage-governance:audit'),
  listExternalCleanupPreviews: () => ipcRenderer.invoke('storage-governance:external:previews'),
  executeExternalCleanup: (key: 'docker-images' | 'docker-containers' | 'docker-build-cache') => ipcRenderer.invoke('storage-governance:external:execute', key),
  onStorageGovernanceProgress: (listener: (event: StorageScanProgress) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, progress: StorageScanProgress): void => listener(progress)
    ipcRenderer.on('storage-governance:scan:progress', wrapped)
    return () => ipcRenderer.removeListener('storage-governance:scan:progress', wrapped)
  },
  getOaSettings: () => ipcRenderer.invoke('settings:oa:get'),
  saveOaSettings: (input: OaSettingsInput) => ipcRenderer.invoke('settings:oa:save', input),
  openOaDocs: () => ipcRenderer.invoke('settings:oa:open-docs'),
  listOaDocuments: () => ipcRenderer.invoke('settings:oa:documents:list'),
  getOaDocumentTasks: (document: OaDocumentRecord) => ipcRenderer.invoke('settings:oa:document:tasks', document),
  getOaBitable: (tableId?: string, viewId?: string) => ipcRenderer.invoke('settings:oa:bitable:get', tableId, viewId),
  saveOaBitableRecord: (input: { tableId: string; recordId?: string; fields: Record<string, unknown> }) => ipcRenderer.invoke('settings:oa:bitable:record:save', input),
  deleteOaBitableRecord: (input: { tableId: string; recordId: string }) => ipcRenderer.invoke('settings:oa:bitable:record:delete', input),
  getLarkBotDashboard: () => ipcRenderer.invoke('settings:oa:lark-bot:dashboard'),
  listLarkBotTasks: (query?: { q?: string; status?: string }) => ipcRenderer.invoke('settings:oa:lark-bot:tasks', query),
  listLarkBotNotifications: () => ipcRenderer.invoke('settings:oa:lark-bot:notifications'),
  getLarkBotSettings: () => ipcRenderer.invoke('settings:oa:lark-bot:settings:get'),
  saveLarkBotSettings: (input: Partial<LarkBotRuntimeSettings>) => ipcRenderer.invoke('settings:oa:lark-bot:settings:save', input),
  syncLarkBot: () => ipcRenderer.invoke('settings:oa:lark-bot:sync'),
  sendLarkBotTestMessage: () => ipcRenderer.invoke('settings:oa:lark-bot:test-message'),
  sendLarkBotReminder: () => ipcRenderer.invoke('settings:oa:lark-bot:reminder'),
  getMenuBarManagerStatus: () => ipcRenderer.invoke('menu-bar-manager:status'),
  saveMenuBarManagerSettings: (input: Partial<MenuBarManagerSettings>) => ipcRenderer.invoke('menu-bar-manager:settings:save', input),
  requestMenuBarManagerPermission: () => ipcRenderer.invoke('menu-bar-manager:permission:request'),
  refreshMenuBarItems: () => ipcRenderer.invoke('menu-bar-manager:items:refresh'),
  showMenuBarHiddenItems: () => ipcRenderer.invoke('menu-bar-manager:section:show'),
  hideMenuBarHiddenItems: () => ipcRenderer.invoke('menu-bar-manager:section:hide'),
  toggleMenuBarHiddenItems: () => ipcRenderer.invoke('menu-bar-manager:section:toggle'),
  onMenuBarManagerChanged: (listener: (status: MenuBarManagerStatus) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, status: MenuBarManagerStatus): void => listener(status)
    ipcRenderer.on('menu-bar-manager:changed', wrapped)
    return () => ipcRenderer.removeListener('menu-bar-manager:changed', wrapped)
  },
  listGithubTokens: () => ipcRenderer.invoke('settings:github-tokens:list'),
  saveGithubToken: (input: GithubTokenInput) => ipcRenderer.invoke('settings:github-tokens:save', input),
  refreshGithubToken: (tokenId: string) => ipcRenderer.invoke('settings:github-tokens:refresh', tokenId),
  deleteGithubToken: (tokenId: string) => ipcRenderer.invoke('settings:github-tokens:delete', tokenId),
  listCodemagicTokens: () => ipcRenderer.invoke('settings:codemagic-tokens:list'),
  saveCodemagicToken: (input: CodemagicTokenInput) => ipcRenderer.invoke('settings:codemagic-tokens:save', input),
  refreshCodemagicToken: (tokenId: string) => ipcRenderer.invoke('settings:codemagic-tokens:refresh', tokenId),
  deleteCodemagicToken: (tokenId: string) => ipcRenderer.invoke('settings:codemagic-tokens:delete', tokenId),
  listCodemagicTeams: (tokenId: string) => ipcRenderer.invoke('codemagic:teams:list', tokenId),
  listCodemagicApps: (input: CodemagicAppListInput) => ipcRenderer.invoke('codemagic:apps:list', input),
  createCodemagicArtifactPublicUrl: (input: CodemagicArtifactPublicUrlInput) => ipcRenderer.invoke('codemagic:artifact:public-url', input),
  listRsaPrivateKeys: () => ipcRenderer.invoke('tools:rsa-private-keys:list'),
  createRsaPrivateKey: (input: RsaPrivateKeyCreateInput) => ipcRenderer.invoke('tools:rsa-private-keys:create', input),
  updateRsaPrivateKey: (input: RsaPrivateKeyUpdateInput) => ipcRenderer.invoke('tools:rsa-private-keys:update', input),
  deleteRsaPrivateKey: (id: string) => ipcRenderer.invoke('tools:rsa-private-keys:delete', id),
  inspectCliEnvironment: () => ipcRenderer.invoke('tools:cli-environment:inspect'),
  repairCliEnvironment: () => ipcRenderer.invoke('tools:cli-environment:repair'),
  previewMonthlyPerformance: (input: MonthlyPerformancePreviewInput) => ipcRenderer.invoke('tools:monthly-performance:preview', input),
  exportMonthlyPerformance: (input: MonthlyPerformanceExportInput) => ipcRenderer.invoke('tools:monthly-performance:export', input),
  listMonthlyPerformanceSessions: () => ipcRenderer.invoke('tools:monthly-performance:sessions:list'),
  createMonthlyPerformanceSession: (input: MonthlyPerformanceSessionCreateInput) => ipcRenderer.invoke('tools:monthly-performance:sessions:create', input),
  sendMonthlyPerformanceSessionMessage: (input: MonthlyPerformanceSessionMessageInput) => ipcRenderer.invoke('tools:monthly-performance:sessions:message', input),
  confirmMonthlyPerformanceSession: (input: { sessionId: string; projectId: string; month: string }) => ipcRenderer.invoke('tools:monthly-performance:sessions:confirm', input),
  exportMonthlyPerformanceSession: (input: MonthlyPerformanceSessionExportInput) => ipcRenderer.invoke('tools:monthly-performance:sessions:export', input),
  generateSshKey: (input: string | SshKeyGenerationInput) => ipcRenderer.invoke('ssh:generate-key', input),
  copySshPublicKey: (publicKeyPath: string) => ipcRenderer.invoke('ssh:copy-public-key', publicKeyPath),
  copySshKeyPath: (path: string, kind: SshKeyKind) => ipcRenderer.invoke('ssh:copy-key-path', path, kind),
  importSshKey: (input: SshKeyImportInput) => ipcRenderer.invoke('ssh:import-key', input),
  deleteSshKey: (path: string, kind: SshKeyKind) => ipcRenderer.invoke('ssh:delete-key', path, kind),
  saveSshPrivateKeyPassphrase: (path: string, passphrase: string) => ipcRenderer.invoke('ssh:save-private-key-passphrase', path, passphrase),
  clearSshPrivateKeyPassphrase: (path: string) => ipcRenderer.invoke('ssh:clear-private-key-passphrase', path),
  fixSshPrivateKeyPermissions: (path: string) => ipcRenderer.invoke('ssh:fix-private-key-permissions', path),
  deriveSshPublicKey: (privateKeyPath: string) => ipcRenderer.invoke('ssh:derive-public-key', privateKeyPath),
  readSshConfig: () => ipcRenderer.invoke('ssh:read-config'),
  writeSshConfig: (content: string) => ipcRenderer.invoke('ssh:write-config', content),
  openSshDirectory: () => ipcRenderer.invoke('ssh:open-directory'),
  listTerminalRemoteGroups: () => ipcRenderer.invoke('terminal:remote-groups:list'),
  saveTerminalRemoteGroup: (input: TerminalRemoteGroupInput) => ipcRenderer.invoke('terminal:remote-group:save', input),
  deleteTerminalRemoteGroup: (groupId: string) => ipcRenderer.invoke('terminal:remote-group:delete', groupId),
  listTerminalRemoteHosts: () => ipcRenderer.invoke('terminal:remote-hosts:list'),
  saveTerminalRemoteHost: (input: TerminalRemoteHostInput) => ipcRenderer.invoke('terminal:remote-host:save', input),
  deleteTerminalRemoteHost: (hostId: string) => ipcRenderer.invoke('terminal:remote-host:delete', hostId),
  getTerminalRemoteSshCommand: (hostId: string) => ipcRenderer.invoke('terminal:remote-host:ssh-command', hostId),
  listTerminals: () => ipcRenderer.invoke('terminal:list'),
  openTerminal: (input?: TerminalCreateInput) => ipcRenderer.invoke('terminal:create', input),
  writeTerminal: (sessionId: string, data: string) => ipcRenderer.invoke('terminal:write', sessionId, data),
  resizeTerminal: (sessionId: string, cols: number, rows: number) => ipcRenderer.invoke('terminal:resize', sessionId, cols, rows),
  closeTerminal: (sessionId: string) => ipcRenderer.invoke('terminal:close', sessionId),
  onTerminalData: (listener: (event: TerminalDataEvent) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: TerminalDataEvent): void => listener(event)
    ipcRenderer.on('terminal:data', wrapped)
    return () => ipcRenderer.removeListener('terminal:data', wrapped)
  },
  onTerminalExit: (listener: (event: TerminalExitEvent) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: TerminalExitEvent): void => listener(event)
    ipcRenderer.on('terminal:exit', wrapped)
    return () => ipcRenderer.removeListener('terminal:exit', wrapped)
  },
  getAppUpdateState: () => ipcRenderer.invoke('app:update:get-state'),
  checkAppUpdate: () => ipcRenderer.invoke('app:update:check'),
  installAppUpdate: () => ipcRenderer.invoke('app:update:install'),
  getAppRuntimeInfo: () => ipcRenderer.invoke('app:runtime-info'),
  startQuickBuild: (input?: QuickBuildStartInput) => ipcRenderer.invoke('quick-build:start', input),
  getQuickBuildTask: () => ipcRenderer.invoke('quick-build:get'),
  cancelQuickBuild: () => ipcRenderer.invoke('quick-build:cancel'),
  restartQuickBuildApp: (input?: QuickBuildRestartInput) => ipcRenderer.invoke('quick-build:restart-app', input),
  onQuickBuildTaskUpdated: (listener: (task: QuickBuildTask | null) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, task: QuickBuildTask | null): void => listener(task)
    ipcRenderer.on('quick-build:task-updated', wrapped)
    return () => ipcRenderer.removeListener('quick-build:task-updated', wrapped)
  },
  onAppUpdateState: (listener: (state: AppUpdateState) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, state: AppUpdateState): void => listener(state)
    ipcRenderer.on('app:update:state', wrapped)
    return () => ipcRenderer.removeListener('app:update:state', wrapped)
  },
  openAppReleases: () => ipcRenderer.invoke('external:open-app-releases'),
  openGitDownload: () => ipcRenderer.invoke('external:open-git-download'),
  openExternalUrl: (url: string) => ipcRenderer.invoke('external:open-url', url)
})
