import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('forgeDesk', {
  listProjects: () => ipcRenderer.invoke('projects:list'),
  createProject: (input: { name: string; workspacePath: string; repositories: ScannedRepository[] }) => ipcRenderer.invoke('projects:create', input),
  updateProject: (input: { id: string; name?: string; workspacePath?: string; description?: string; owner?: string }) => ipcRenderer.invoke('projects:update', input),
  deleteProject: (projectId: string) => ipcRenderer.invoke('projects:delete', projectId),
  listRepositories: (projectId?: string) => ipcRenderer.invoke('repositories:list', projectId),
  getRepositoryDetail: (repositoryId: string) => ipcRenderer.invoke('repository:detail', repositoryId),
  listRepositoryCommits: (repositoryId: string, options?: { startDate?: string; endDate?: string; branchName?: string }) =>
    ipcRenderer.invoke('repository:commits', repositoryId, options),
  getRepositoryCommitGraph: (repositoryId: string, options?: { startDate?: string; endDate?: string; branchName?: string }) =>
    ipcRenderer.invoke('repository:commit-graph', repositoryId, options),
  syncRepositoryRemote: (repositoryId: string) => ipcRenderer.invoke('repository:sync-remote', repositoryId),
  saveRepositoryRemote: (input: RepositoryRemoteInput) => ipcRenderer.invoke('repository:remote:save', input),
  deleteRepositoryRemote: (repositoryId: string, remoteName: string) => ipcRenderer.invoke('repository:remote:delete', repositoryId, remoteName),
  fetchRepositoryRemote: (repositoryId: string, remoteName?: string) => ipcRenderer.invoke('repository:remote:fetch', repositoryId, remoteName),
  switchRepositoryBranch: (repositoryId: string, input: GitBranchSwitchInput) => ipcRenderer.invoke('repository:branch:switch', repositoryId, input),
  runRepositoryGitCommand: (input: GitCommandRequest) => ipcRenderer.invoke('repository:git-command', input),
  getRepositoryWorkspaceStatus: (repositoryId: string) => ipcRenderer.invoke('repository:workspace-status', repositoryId),
  gitAdd: (repositoryId: string, input: GitAddInput) => ipcRenderer.invoke('repository:git-add', repositoryId, input),
  gitCommit: (repositoryId: string, input: GitCommitInput) => ipcRenderer.invoke('repository:git-commit', repositoryId, input),
  gitPush: (repositoryId: string, input: GitPushInput) => ipcRenderer.invoke('repository:git-push', repositoryId, input),
  analyzeRepositoryMerge: (repositoryId: string, input: GitMergeAnalysisInput) => ipcRenderer.invoke('repository:merge-analysis', repositoryId, input),
  gitMerge: (repositoryId: string, input: GitMergeInput) => ipcRenderer.invoke('repository:git-merge', repositoryId, input),
  suggestCommitMessage: (repositoryId: string, input: GitCommitMessageInput) => ipcRenderer.invoke('repository:commit-message:suggest', repositoryId, input),
  prepareRepositoryRelease: (repositoryId: string, input?: RepositoryReleasePrepareInput) => ipcRenderer.invoke('repository:release:prepare', repositoryId, input),
  recommendRepositoryReleaseTag: (repositoryId: string) => ipcRenderer.invoke('repository:release-tag:recommend', repositoryId),
  suggestRepositoryRelease: (repositoryId: string, input?: RepositoryReleaseSuggestionInput) => ipcRenderer.invoke('repository:release:suggest', repositoryId, input),
  publishRepositoryRelease: (repositoryId: string, input: RepositoryReleasePublishInput) => ipcRenderer.invoke('repository:release:publish', repositoryId, input),
  startRepositoryReleasePublishTask: (repositoryId: string, input: RepositoryReleasePublishInput) => ipcRenderer.invoke('repository:release-publish-task:start', repositoryId, input),
  listRepositoryReleasePublishTasks: (repositoryId?: string) => ipcRenderer.invoke('repository:release-publish-tasks:list', repositoryId),
  getRepositoryReleasePublishTask: (taskId: string) => ipcRenderer.invoke('repository:release-publish-task:get', taskId),
  cancelRepositoryReleasePublishTask: (taskId: string) => ipcRenderer.invoke('repository:release-publish-task:cancel', taskId),
  suggestConflictResolution: (repositoryId: string, filePath: string) => ipcRenderer.invoke('repository:conflict:suggest', repositoryId, filePath),
  applyConflictResolution: (repositoryId: string, filePath: string, content: string) => ipcRenderer.invoke('repository:conflict:apply', repositoryId, filePath, content),
  listRepositoryCommitFiles: (repositoryId: string, commitHash: string) => ipcRenderer.invoke('repository:commit-files', repositoryId, commitHash),
  getRepositoryCommitDiff: (repositoryId: string, commitHash: string, filePath: string, oldPath?: string, status?: string) =>
    ipcRenderer.invoke('repository:commit-diff', repositoryId, commitHash, filePath, oldPath, status),
  getProjectSummary: (projectId: string, range?: { startDate?: string; endDate?: string }) => ipcRenderer.invoke('project:summary', projectId, range),
  analyzeProjectGit: (projectId: string) => ipcRenderer.invoke('project:analyze-git', projectId),
  listProjectPeople: (projectId: string) => ipcRenderer.invoke('project:people', projectId),
  listProjectContributorIdentities: (projectId: string) => ipcRenderer.invoke('project:contributor-identities', projectId),
  listProjectBranchTags: (projectId: string) => ipcRenderer.invoke('project:branch-tags', projectId),
  saveProjectBranchTag: (input: { id?: string; projectId: string; label: string; branchName: string; color: string }) => ipcRenderer.invoke('project:branch-tag:save', input),
  deleteProjectBranchTag: (projectId: string, tagId: string) => ipcRenderer.invoke('project:branch-tag:delete', projectId, tagId),
  getPlaneSettings: () => ipcRenderer.invoke('plane:settings:get'),
  savePlaneSettings: (input: PlaneSettingsInput) => ipcRenderer.invoke('plane:settings:save', input),
  testPlaneSettings: (input?: PlaneSettingsInput) => ipcRenderer.invoke('plane:settings:test', input),
  listPlaneProjects: (workspaceSlug: string) => ipcRenderer.invoke('plane:projects:list', workspaceSlug),
  getProjectPlaneBinding: (projectId: string) => ipcRenderer.invoke('plane:binding:get', projectId),
  saveProjectPlaneBinding: (input: PlaneProjectBindingInput) => ipcRenderer.invoke('plane:binding:save', input),
  deleteProjectPlaneBinding: (projectId: string) => ipcRenderer.invoke('plane:binding:delete', projectId),
  getPlaneProjectContent: (projectId: string) => ipcRenderer.invoke('plane:project-content:get', projectId),
  openPlane: (projectId?: string) => ipcRenderer.invoke('plane:open', projectId),
  listServiceConnections: () => ipcRenderer.invoke('service:connections:list'),
  saveServiceConnection: (input: ServiceConnectionInput) => ipcRenderer.invoke('service:connection:save', input),
  deleteServiceConnection: (connectionId: string) => ipcRenderer.invoke('service:connection:delete', connectionId),
  testServiceConnection: (connectionId: string) => ipcRenderer.invoke('service:connection:test', connectionId),
  listAllProjectServices: () => ipcRenderer.invoke('service:services:list'),
  listProjectServices: (projectId: string) => ipcRenderer.invoke('project:services:list', projectId),
  saveProjectService: (input: ProjectServiceInput) => ipcRenderer.invoke('project:service:save', input),
  saveServiceExternalProjectAlias: (input: ServiceExternalProjectAliasInput) => ipcRenderer.invoke('service:external-project:alias:save', input),
  bindProjectService: (input: { projectId: string; serviceId: string; repositoryId?: string }) => ipcRenderer.invoke('project:service:bind', input),
  syncProjectServices: (connectionId?: string) => ipcRenderer.invoke('project:services:sync', connectionId),
  checkProjectServices: (projectId?: string) => ipcRenderer.invoke('service:monitor:check', projectId),
  listLatestServiceMonitorChecks: (projectId: string) => ipcRenderer.invoke('service:monitor:latest', projectId),
  listServiceMonitorHistory: (projectId: string) => ipcRenderer.invoke('service:monitor:history', projectId),
  listAllServiceMonitorHistory: () => ipcRenderer.invoke('service:monitor:history:all'),
  listServiceEnvironmentLogs: (serviceId: string, environmentName: string) => ipcRenderer.invoke('service:environment:logs', serviceId, environmentName),
  listCachedServiceDeployments: (serviceId: string, options?: ServiceDeploymentListOptions) => ipcRenderer.invoke('service:deployments:cached:list', serviceId, options),
  listServiceDeployments: (serviceId: string, options?: ServiceDeploymentListOptions) => ipcRenderer.invoke('service:deployments:list', serviceId, options),
  runServiceDeploymentAction: (serviceId: string, input: VercelDeploymentActionInput) => ipcRenderer.invoke('service:deployment:action', serviceId, input),
  listServiceEnvVars: (serviceId: string) => ipcRenderer.invoke('service:env:list', serviceId),
  revealServiceEnvVar: (serviceId: string, envVarId: string) => ipcRenderer.invoke('service:env:reveal', serviceId, envVarId),
  saveServiceEnvVar: (serviceId: string, input: VercelEnvVarInput) => ipcRenderer.invoke('service:env:save', serviceId, input),
  deleteServiceEnvVar: (serviceId: string, envVarId: string) => ipcRenderer.invoke('service:env:delete', serviceId, envVarId),
  addServiceDomain: (serviceId: string, input: VercelDomainInput) => ipcRenderer.invoke('service:domain:add', serviceId, input),
  removeServiceDomain: (serviceId: string, domain: string, removeRedirects?: boolean) => ipcRenderer.invoke('service:domain:remove', serviceId, domain, removeRedirects),
  verifyServiceDomain: (serviceId: string, domain: string) => ipcRenderer.invoke('service:domain:verify', serviceId, domain),
  inspectServiceDomainConfig: (serviceId: string, domain: string) => ipcRenderer.invoke('service:domain:config', serviceId, domain),
  listServiceRuntimeLogs: (serviceId: string, environmentName: string) => ipcRenderer.invoke('service:runtime:logs', serviceId, environmentName),
  getDockerSnapshot: () => ipcRenderer.invoke('docker:snapshot'),
  saveDockerResourceNote: (input: DockerResourceNoteInput) => ipcRenderer.invoke('docker:note:save', input),
  deleteDockerResourceNote: (resourceType: DockerResourceType, resourceKey: string) => ipcRenderer.invoke('docker:note:delete', resourceType, resourceKey),
  startDockerWatch: () => ipcRenderer.invoke('docker:watch:start'),
  stopDockerWatch: () => ipcRenderer.invoke('docker:watch:stop'),
  onDockerChanged: (listener: (event: DockerEventSummary) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: DockerEventSummary): void => listener(event)
    ipcRenderer.on('docker:changed', wrapped)
    return () => ipcRenderer.removeListener('docker:changed', wrapped)
  },
  onDockerWatchError: (listener: (event: { message: string }) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: { message: string }): void => listener(event)
    ipcRenderer.on('docker:watch:error', wrapped)
    return () => ipcRenderer.removeListener('docker:watch:error', wrapped)
  },
  saveProjectPerson: (input: { id?: string; projectId: string; displayName: string; role?: string; identities: Array<{ name: string; email: string }> }) =>
    ipcRenderer.invoke('project:person:save', input),
  deleteProjectPerson: (projectId: string, personId: string) => ipcRenderer.invoke('project:person:delete', projectId, personId),
  scanRepositories: (paths: string[]) => ipcRenderer.invoke('repositories:scan', paths),
  scanWorkspace: (rootPath: string) => ipcRenderer.invoke('repositories:scan-workspace', rootPath),
  configureRepositoryIdentity: (localPath: string, identity: { userName: string; userEmail: string }) =>
    ipcRenderer.invoke('repository:configure-identity', localPath, identity),
  clearRepositoryIdentity: (localPath: string) => ipcRenderer.invoke('repository:clear-identity', localPath),
  selectDirectory: () => ipcRenderer.invoke('dialog:select-directory'),
  selectFile: () => ipcRenderer.invoke('dialog:select-file'),
  getGitSetupStatus: () => ipcRenderer.invoke('git:setup-status'),
  configureGitIdentity: (identity: { userName: string; userEmail: string }) => ipcRenderer.invoke('git:configure-identity', identity),
  getAiSettings: () => ipcRenderer.invoke('settings:ai:get'),
  saveAiSettings: (input: AiSettingsInput) => ipcRenderer.invoke('settings:ai:save', input),
  listGithubTokens: () => ipcRenderer.invoke('settings:github-tokens:list'),
  saveGithubToken: (input: GithubTokenInput) => ipcRenderer.invoke('settings:github-tokens:save', input),
  refreshGithubToken: (tokenId: string) => ipcRenderer.invoke('settings:github-tokens:refresh', tokenId),
  deleteGithubToken: (tokenId: string) => ipcRenderer.invoke('settings:github-tokens:delete', tokenId),
  listRsaPrivateKeys: () => ipcRenderer.invoke('tools:rsa-private-keys:list'),
  createRsaPrivateKey: (input: RsaPrivateKeyCreateInput) => ipcRenderer.invoke('tools:rsa-private-keys:create', input),
  updateRsaPrivateKey: (input: RsaPrivateKeyUpdateInput) => ipcRenderer.invoke('tools:rsa-private-keys:update', input),
  deleteRsaPrivateKey: (id: string) => ipcRenderer.invoke('tools:rsa-private-keys:delete', id),
  generateSshKey: (input: string | SshKeyGenerationInput) => ipcRenderer.invoke('ssh:generate-key', input),
  copySshPublicKey: (publicKeyPath: string) => ipcRenderer.invoke('ssh:copy-public-key', publicKeyPath),
  copySshKeyPath: (path: string, kind: SshKeyKind) => ipcRenderer.invoke('ssh:copy-key-path', path, kind),
  importSshKey: (input: SshKeyImportInput) => ipcRenderer.invoke('ssh:import-key', input),
  deleteSshKey: (path: string, kind: SshKeyKind) => ipcRenderer.invoke('ssh:delete-key', path, kind),
  saveSshPrivateKeyPassphrase: (path: string, passphrase: string) => ipcRenderer.invoke('ssh:save-private-key-passphrase', path, passphrase),
  clearSshPrivateKeyPassphrase: (path: string) => ipcRenderer.invoke('ssh:clear-private-key-passphrase', path),
  fixSshPrivateKeyPermissions: (path: string) => ipcRenderer.invoke('ssh:fix-private-key-permissions', path),
  deriveSshPublicKey: (privateKeyPath: string) => ipcRenderer.invoke('ssh:derive-public-key', privateKeyPath),
  readSshConfig: () => ipcRenderer.invoke('ssh:read-config'),
  writeSshConfig: (content: string) => ipcRenderer.invoke('ssh:write-config', content),
  openSshDirectory: () => ipcRenderer.invoke('ssh:open-directory'),
  listTerminalRemoteGroups: () => ipcRenderer.invoke('terminal:remote-groups:list'),
  saveTerminalRemoteGroup: (input: TerminalRemoteGroupInput) => ipcRenderer.invoke('terminal:remote-group:save', input),
  deleteTerminalRemoteGroup: (groupId: string) => ipcRenderer.invoke('terminal:remote-group:delete', groupId),
  listTerminalRemoteHosts: () => ipcRenderer.invoke('terminal:remote-hosts:list'),
  saveTerminalRemoteHost: (input: TerminalRemoteHostInput) => ipcRenderer.invoke('terminal:remote-host:save', input),
  deleteTerminalRemoteHost: (hostId: string) => ipcRenderer.invoke('terminal:remote-host:delete', hostId),
  getTerminalRemoteSshCommand: (hostId: string) => ipcRenderer.invoke('terminal:remote-host:ssh-command', hostId),
  openTerminal: (input?: TerminalCreateInput) => ipcRenderer.invoke('terminal:create', input),
  writeTerminal: (sessionId: string, data: string) => ipcRenderer.invoke('terminal:write', sessionId, data),
  resizeTerminal: (sessionId: string, cols: number, rows: number) => ipcRenderer.invoke('terminal:resize', sessionId, cols, rows),
  closeTerminal: (sessionId: string) => ipcRenderer.invoke('terminal:close', sessionId),
  onTerminalData: (listener: (event: TerminalDataEvent) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: TerminalDataEvent): void => listener(event)
    ipcRenderer.on('terminal:data', wrapped)
    return () => ipcRenderer.removeListener('terminal:data', wrapped)
  },
  onTerminalExit: (listener: (event: TerminalExitEvent) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, event: TerminalExitEvent): void => listener(event)
    ipcRenderer.on('terminal:exit', wrapped)
    return () => ipcRenderer.removeListener('terminal:exit', wrapped)
  },
  getAppUpdateState: () => ipcRenderer.invoke('app:update:get-state'),
  checkAppUpdate: () => ipcRenderer.invoke('app:update:check'),
  installAppUpdate: () => ipcRenderer.invoke('app:update:install'),
  onAppUpdateState: (listener: (state: AppUpdateState) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, state: AppUpdateState): void => listener(state)
    ipcRenderer.on('app:update:state', wrapped)
    return () => ipcRenderer.removeListener('app:update:state', wrapped)
  },
  openAppReleases: () => ipcRenderer.invoke('external:open-app-releases'),
  openGitDownload: () => ipcRenderer.invoke('external:open-git-download')
})
